// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unhlmjdqdqobyztmdncu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuaGxtamRxZHFvYnl6dG1kbmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyODQ4MjgsImV4cCI6MjA2NDg2MDgyOH0.DsSsrX4hwBHf7GjPGTRbPsfRTMnD7OBjQK28peuR4TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);